name: Deploy to Lolipop

on:
  push:
    branches:
      - production  # productionブランチにPushされたらロリポップへ

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to Lolipop
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ secrets.LOLIPOP_GIT_URL }}
          ssh_private_key: ${{ secrets.LOLIPOP_SSH_KEY }}